/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public\assets\models\pinkForest.glb 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function PinkForest(props) {
  const { nodes, materials } = useGLTF("/assets/models/pinkForest.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[0, -1.571, 0]}>
        <mesh
          geometry={nodes.Cube_Material016_0.geometry}
          material={materials.brown}
        />
        <mesh
          geometry={nodes.Cube_Material016_0_1.geometry}
          material={materials["off white"]}
        />
        <mesh
          geometry={nodes.Cube_Material016_0_2.geometry}
          material={materials.black}
        />
        <mesh
          geometry={nodes.Cube_Material016_0_3.geometry}
          material={materials["Material.003"]}
        />
        <mesh
          geometry={nodes.Cube_Material016_0_4.geometry}
          material={materials.black}
        />
        <mesh
          geometry={nodes.Cube_Material016_0_5.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          geometry={nodes.Cube_Material016_0_6.geometry}
          material={materials.brown}
        />
        <mesh
          geometry={nodes.Cube_Material016_0_7.geometry}
          material={materials["Material.011"]}
        />
        <mesh
          geometry={nodes.Cube_Material016_0_8.geometry}
          material={materials["Material.012"]}
        />
        <mesh
          geometry={nodes.Cube_Material016_0_9.geometry}
          material={materials["Material.009"]}
        />
        <mesh
          geometry={nodes.Cube_Material016_0_10.geometry}
          material={materials["Material.008"]}
        />
        <group
          position={[1.887, 5.632, 0.861]}
          rotation={[-Math.PI, 1.396, -Math.PI]}
        >
          <mesh geometry={nodes.Drone001.geometry} material={materials.body} />
          <mesh
            geometry={nodes.Drone001_1.geometry}
            material={materials.blue}
          />
          <mesh geometry={nodes.Drone001_2.geometry} material={materials.cam} />
          <mesh
            geometry={nodes.Drone001_3.geometry}
            material={materials.metal}
          />
          <mesh geometry={nodes.Drone001_4.geometry} material={materials.red} />
          <mesh
            geometry={nodes.Drone001_5.geometry}
            material={materials.tail}
          />
        </group>
        <group
          position={[3.86, 2.237, 1.51]}
          rotation={[-Math.PI, 1.396, -Math.PI]}
        >
          <mesh geometry={nodes.Drone002.geometry} material={materials.body} />
          <mesh
            geometry={nodes.Drone002_1.geometry}
            material={materials.blue}
          />
          <mesh geometry={nodes.Drone002_2.geometry} material={materials.cam} />
          <mesh
            geometry={nodes.Drone002_3.geometry}
            material={materials.metal}
          />
          <mesh geometry={nodes.Drone002_4.geometry} material={materials.red} />
          <mesh
            geometry={nodes.Drone002_5.geometry}
            material={materials.tail}
          />
        </group>
        <group
          position={[-1.438, 3.692, -1.069]}
          rotation={[-Math.PI, 1.396, -Math.PI]}
        >
          <mesh geometry={nodes.Drone.geometry} material={materials.body} />
          <mesh geometry={nodes.Drone_1.geometry} material={materials.blue} />
          <mesh geometry={nodes.Drone_2.geometry} material={materials.cam} />
          <mesh geometry={nodes.Drone_3.geometry} material={materials.metal} />
          <mesh geometry={nodes.Drone_4.geometry} material={materials.red} />
          <mesh geometry={nodes.Drone_5.geometry} material={materials.tail} />
        </group>
        <group position={[-5, 5, 0]} scale={[0.03, 1.1, 1.76]}>
          <mesh
            geometry={nodes.Cube.geometry}
            material={materials["off white"]}
          />
          <mesh geometry={nodes.Cube_1.geometry} material={materials.black} />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/assets/models/pinkForest.glb");
