/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public\assets\models\pod2.glb 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Pod2(props) {
  const { nodes, materials } = useGLTF("/assets/models/pod2.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.pod2.geometry} material={materials["mid grey"]}>
        <mesh geometry={nodes.car1.geometry} material={materials.car1} />
        <mesh geometry={nodes.car2.geometry} material={materials.car2} />
        <mesh geometry={nodes.remote002.geometry} material={materials.black} />
        <mesh geometry={nodes["this"].geometry} material={materials.black}>
          <mesh
            geometry={nodes.Text002.geometry}
            material={materials["off white"]}
          />
        </mesh>
        <mesh geometry={nodes.Vizor002.geometry} material={materials.black} />
        <mesh geometry={nodes.Drone_1.geometry} material={materials.body} />
        <mesh geometry={nodes.Drone_2.geometry} material={materials.blue} />
        <mesh geometry={nodes.Drone_3.geometry} material={materials.cam} />
        <mesh geometry={nodes.Drone_4.geometry} material={materials.metal} />
        <mesh geometry={nodes.Drone_5.geometry} material={materials.red} />
        <mesh geometry={nodes.Drone_6.geometry} material={materials.tail} />
        <mesh
          geometry={nodes.Body010.geometry}
          material={materials["off white"]}
        />
        <mesh
          geometry={nodes.Body010_1.geometry}
          material={materials["mid grey"]}
        />
        <mesh
          geometry={nodes.Body008.geometry}
          material={materials["off white"]}
        />
        <mesh
          geometry={nodes.Body008_1.geometry}
          material={materials["mid grey"]}
        />
        <mesh
          geometry={nodes.Body009.geometry}
          material={materials["off white"]}
        />
        <mesh
          geometry={nodes.Body009_1.geometry}
          material={materials["mid grey"]}
        />
        <mesh
          geometry={nodes.Body011.geometry}
          material={materials["off white"]}
        />
        <mesh
          geometry={nodes.Body011_1.geometry}
          material={materials["mid grey"]}
        />
        <mesh
          geometry={nodes.Body007.geometry}
          material={materials["off white"]}
        />
        <mesh
          geometry={nodes.Body007_1.geometry}
          material={materials["mid grey"]}
        />
        <mesh geometry={nodes.motors_1.geometry} material={materials.metal} />
        <mesh geometry={nodes.motors_2.geometry} material={materials.gold} />
        <mesh geometry={nodes.wing1_1.geometry} material={materials.fan} />
        <mesh geometry={nodes.wing1_2.geometry} material={materials.gold} />
        <mesh geometry={nodes.wing2_1.geometry} material={materials.fan} />
        <mesh geometry={nodes.wing2_2.geometry} material={materials.gold} />
        <mesh geometry={nodes.wing3_1.geometry} material={materials.fan} />
        <mesh geometry={nodes.wing3_2.geometry} material={materials.gold} />
        <mesh geometry={nodes.wing4_1.geometry} material={materials.fan} />
        <mesh geometry={nodes.wing4_2.geometry} material={materials.gold} />
      </mesh>
    </group>
  );
}

useGLTF.preload("/assets/models/pod2.glb");
